### PR TITLE
Use KillWithFire to stop consul on Windows

### PR DESCRIPTION
**Pull request by stefanschneider**
This is related to this PR: https://github.com/cloudfoundry-incubator/consuladapter/pull/1

[#104201496] https://www.pivotaltracker.com/story/show/104201496

Signed-off-by: John Shahid <jshahid@pivotal.io>

### CODE REVIEW

**Comment by ematpl** [comment]
Thanks, @stefanschneider! Prioritizing for the Diego team to review.

Best,
Eric

**Comment by cwlbraa** [comment]
Is there any reason this problem wasn't handled with build tags? As much as I love KillWithFire functions, it seems a bit cumbersome to handle this at runtime when it could be handled at compile time. This could be as simple as breaking the "stop" function out into a windows-only file and an everything else file.

**Comment by cwlbraa** [comment]
We believe we've resolved this pull request with https://github.com/cloudfoundry-incubator/consuladapter/commit/581f4f7caa186a4f0185eebef01b7065b06177be , but we have no windows cells to validate on. Let us know if it doesn't work for you. For now, I'm closing this PR.

**Comment by stefanschneider** [comment]
I'll check it again. 
All this commits where tested together ~ 1 month ago and then we chained the PRs based on their dependencies.

**Pull request closed without merging**
